@startuml
entity "Heroes" {
    * heroe_id : Integer [PK]
    --
    nombre : String
}

entity "Matchups" {
    * matchup_id : Integer [PK]
    --
    heroe_id : Integer [FK]
    enemigo_id : Integer [FK]
    games_played : Integer
    wins : Integer
    winrate : Float [calculated]
}

Heroes ||--o{ "Matchups" : enfrentamientos
@enduml